Update doc gen script to get dev/rc version

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -85,20 +85,24 @@ jobs:
           export DOCS_PATH=$(echo $BODY | head -n 1 | cut -d'/' -f3 | xargs)  # use xargs to trim ws/newline chars
           echo "Git short hash: $GIT_HASH"
           echo "Issue URL base: $ISSUE_URL"
-          if [ ! $(echo "$DOCS_PATH" | grep -P "v([0-9]+\.){2}[0-9]+") ]; then
-            gh issue comment -R $ISSUE_URL $ISSUE_NUMBER --body "Docs version is malformed, it should be v\d+\.\d+\.\d+ format";
-            exit 1;
+          # Extract version from DOCS_PATH
+          VERSION=$(echo "$DOCS_PATH" | grep -oP "v([0-9]+\.){2}[0-9]+(\.(rc|dev)[0-9]+)?")
+          if [ -z "$VERSION" ]; then
+            echo "Docs version is malformed. It should be in the format v\d+\.\d+\.\d+(rc|dev)\d+" > error_message.txt
+            gh issue comment -R $ISSUE_URL $ISSUE_NUMBER --body-file error_message.txt
+            exit 1
           fi
+          echo "Extracted Version: $VERSION"
           # install documentation requirements
           pip install -r ./docs/requirements.txt
           # generate documentation
-          mkdocs build --site-dir ../$DOCS_PATH
+          mkdocs build --site-dir ../$VERSION
           # checkout to gh-pages
           git checkout gh-pages
-          cp -r ../$DOCS_PATH .
+          cp -r ../$VERSION .
           # update latest symbolic link
           rm latest
-          ln -s $DOCS_PATH latest
+          ln -s $VERSION latest
           git add .
           # if no change in docs repo
           if git diff --cached --exit-code > /dev/null; then echo "no change"; exit 1; fi
@@ -115,6 +119,6 @@ jobs:
           echo "RUN_ID: $RUN_ID"
           gh run watch $RUN_ID
           # github comment
-          gh issue comment -R $ISSUE_URL $ISSUE_NUMBER --body "Documentation generated by $DOCS_PATH successfully!
+          gh issue comment -R $ISSUE_URL $ISSUE_NUMBER --body "Documentation generated by $VERSION successfully!
           Documentation commit: https://github.com/furiosa-ai/furiosa-models/commit/$DOCS_COMMIT
-          Documentation URL: https://furiosa-ai.github.io/furiosa-models/$DOCS_PATH/"
+          Documentation URL: https://furiosa-ai.github.io/furiosa-models/$VERSION/"
